import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
    en: {
        home: 'Home',
        hotels: 'Hotels',
        destinations: 'Destinations',
        about: 'About Us',
        signIn: 'Sign In',
        register: 'Register',
        heroTitle: 'Find Your Next',
        heroSubtitle: 'Perfect Getaway',
        heroText: 'Discover luxury hotels and unique stays around the world.',
        searchPlaceholder: 'Where do you want to go?',
        searchBtn: 'Search',
        popularDestinations: 'Popular Destinations',
        from: 'From',
        night: 'night',
        loginTitle: 'Welcome Back',
        loginSubtitle: 'Enter your credentials to access your account',
        emailLabel: 'Email Address',
        passwordLabel: 'Password',
        loginBtn: 'Sign In',
        noAccount: "Don't have an account?",
        registerLink: 'Sign up',
        registerTitle: 'Create Account',
        registerSubtitle: 'Join us to book your dream vacation',
        firstNameLabel: 'First Name',
        lastNameLabel: 'Last Name',
        registerBtn: 'Create Account',
        hasAccount: 'Already have an account?',
        loginLink: 'Sign in',
        // Hotel Details
        backToHotels: 'Back to Hotels',
        perNight: '/night',
        aboutHotel: 'About this hotel',
        amenities: 'Amenities',
        bookNow: 'Book Now',
        location: 'Location',
        availability: 'Availability',
        available: 'Available',
        notAvailable: 'Not Available',
        needHelp: 'Need help?',
        contactInfo: 'Contact us for any questions about this hotel',
        contactSupport: 'Contact Support',
        loadingHotel: 'Loading hotel details...',
        hotelNotFound: 'Hotel not found',
        hotelNotFoundText: "The hotel you're looking for could not be found.",
        rating: 'Rating',
        // About Us Page
        aboutUsHero: 'About Us',
        aboutUsSubtitle: 'Discover the story behind Petoria',
        ourStory: 'Our Story',
        ourStoryText: 'Founded with a passion for travel and hospitality, Petoria has been connecting travelers with exceptional accommodations since our inception. We believe that every journey deserves a perfect place to stay, and we\'re committed to making that happen.',
        ourMission: 'Our Mission',
        ourMissionText: 'To provide travelers with seamless access to quality accommodations worldwide, while supporting local hospitality businesses and creating memorable experiences.',
        ourVision: 'Our Vision',
        ourVisionText: 'To become the most trusted platform for hotel bookings, known for our exceptional service, innovative technology, and commitment to sustainable tourism.',
        ourValues: 'Our Values',
        valueQuality: 'Quality',
        valueQualityText: 'We partner only with verified, high-quality hotels to ensure the best experience.',
        valueTrust: 'Trust',
        valueTrustText: 'Transparency and honesty in all our dealings with customers and partners.',
        valueInnovation: 'Innovation',
        valueInnovationText: 'Continuously improving our platform to serve you better.',
        valueSustainability: 'Sustainability',
        valueSustainabilityText: 'Promoting eco-friendly practices in the hospitality industry.',
        meetOurTeam: 'Meet Our Team',
        teamMember1Name: 'John Smith',
        teamMember1Role: 'CEO & Founder',
        teamMember2Name: 'Sarah Johnson',
        teamMember2Role: 'Head of Operations',
        teamMember3Name: 'Michael Chen',
        teamMember3Role: 'Chief Technology Officer',
        teamMember4Name: 'Emily Rodriguez',
        teamMember4Role: 'Customer Experience Lead',
        joinUs: 'Join Us on Our Journey',
        joinUsText: 'Whether you\'re looking for your next getaway or want to partner with us, we\'re here to help.',
        exploreHotels: 'Explore Hotels',
        contactUs: 'Contact Us'
    },
    bg: {
        home: 'Начало',
        hotels: 'Хотели',
        destinations: 'Дестинации',
        about: 'За Нас',
        signIn: 'Вход',
        register: 'Регистрация',
        heroTitle: 'Открий Своята',
        heroSubtitle: 'Перфектна Почивка',
        heroText: 'Открийте луксозни хотели и уникални места по света.',
        searchPlaceholder: 'Къде искате да отидете?',
        searchBtn: 'Търси',
        popularDestinations: 'Популярни Дестинации',
        from: 'От',
        night: 'нощувка',
        loginTitle: 'Добре дошли отново',
        loginSubtitle: 'Въведете данните си за достъп',
        emailLabel: 'Имейл Адрес',
        passwordLabel: 'Парола',
        loginBtn: 'Вход',
        noAccount: 'Нямате акаунт?',
        registerLink: 'Регистрирайте се',
        registerTitle: 'Създай Акаунт',
        registerSubtitle: 'Присъединете се към нас за мечтаната ваканция',
        firstNameLabel: 'Име',
        lastNameLabel: 'Фамилия',
        registerBtn: 'Създай Акаунт',
        hasAccount: 'Вече имате акаунт?',
        loginLink: 'Влезте',
        // Hotel Details
        backToHotels: 'Назад към Хотели',
        perNight: '/нощувка',
        aboutHotel: 'За хотела',
        amenities: 'Удобства',
        bookNow: 'Резервирай сега',
        location: 'Локация',
        availability: 'Наличност',
        available: 'Налично',
        notAvailable: 'Не е налично',
        needHelp: 'Нужда от помощ?',
        contactInfo: 'Свържете се с нас за въпроси относно този хотел',
        contactSupport: 'Свържете се с поддръжка',
        loadingHotel: 'Зареждане на детайли за хотела...',
        hotelNotFound: 'Хотелът не е намерен',
        hotelNotFoundText: 'Хотелът, който търсите, не може да бъде намерен.',
        rating: 'Рейтинг',
        // About Us Page
        aboutUsHero: 'За нас',
        aboutUsSubtitle: 'Открийте историята зад Petoria',
        ourStory: 'Нашата история',
        ourStoryText: 'Основани със страст към пътуванията и хотелиерството, Petoria свързва пътуващите с изключителни места за настаняване от самото си създаване. Вярваме, че всяко пътуване заслужава перфектно място за престой и сме ангажирани да направим това възможно.',
        ourMission: 'Нашата мисия',
        ourMissionText: 'Да предоставим на пътуващите безпроблемен достъп до качествени места за настаняване по целия свят, като същевременно подкрепяме местния хотелиерски бизнес и създаваме незабравими преживявания.',
        ourVision: 'Нашата визия',
        ourVisionText: 'Да станем най-доверената платформа за резервации на хотели, позната с изключителното си обслужване, иновативни технологии и ангажираност към устойчив туризъм.',
        ourValues: 'Нашите ценности',
        valueQuality: 'Качество',
        valueQualityText: 'Партнираме само с проверени, висококачествени хотели за най-доброто изживяване.',
        valueTrust: 'Доверие',
        valueTrustText: 'Прозрачност и честност във всичките ни отношения с клиенти и партньори.',
        valueInnovation: 'Иновация',
        valueInnovationText: 'Непрекъснато подобряваме платформата си, за да ви обслужваме по-добре.',
        valueSustainability: 'Устойчивост',
        valueSustainabilityText: 'Промотираме екологични практики в хотелиерската индустрия.',
        meetOurTeam: 'Запознайте се с нашия екип',
        teamMember1Name: 'Иван Петров',
        teamMember1Role: 'Изпълнителен директор и основател',
        teamMember2Name: 'Мария Георгиева',
        teamMember2Role: 'Ръководител операции',
        teamMember3Name: 'Стефан Димитров',
        teamMember3Role: 'Главен технологичен директор',
        teamMember4Name: 'Елена Иванова',
        teamMember4Role: 'Ръководител клиентско обслужване',
        joinUs: 'Присъединете се към нашето пътуване',
        joinUsText: 'Независимо дали търсите следващата си почивка или искате да партнирате с нас, ние сме тук, за да помогнем.',
        exploreHotels: 'Разгледайте хотелите',
        contactUs: 'Свържете се с нас'
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage((prev) => (prev === 'en' ? 'bg' : 'en'));
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
