import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
    en: {
        home: 'Home',
        hotels: 'Hotels',
        destinations: 'Destinations',
        about: 'About Us',
        signIn: 'Sign In',
        register: 'Register',
        heroTitle: 'Find Your Next',
        heroSubtitle: 'Perfect Getaway',
        heroText: 'Discover luxury hotels and unique stays around the world.',
        searchPlaceholder: 'Where do you want to go?',
        findPerfectStay: 'Find Your Perfect Stay',
        discoverAmazing: 'Discover amazing hotels with the best amenities and prices',
        searchBtn: 'Search',
        popularDestinations: 'Popular Destinations',
        destMaldives: 'Maldives',
        destMaldivesDesc: 'Experience the ultimate luxury in overwater bungalows.',
        destSantorini: 'Santorini, Greece',
        destSantoriniDesc: 'Breathtaking views and white-washed architecture.',
        destBali: 'Bali, Indonesia',
        destBaliDesc: 'Tropical paradise with rich culture and stunning beaches.',
        from: 'From',
        night: 'night',
        loginTitle: 'Welcome Back',
        loginSubtitle: 'Enter your credentials to access your account',
        emailLabel: 'Email Address',
        passwordLabel: 'Password',
        loginBtn: 'Sign In',
        noAccount: "Don't have an account?",
        registerLink: 'Sign up',
        registerTitle: 'Create Account',
        registerSubtitle: 'Join us to book your dream vacation',
        firstNameLabel: 'First Name',
        lastNameLabel: 'Last Name',
        registerBtn: 'Create Account',
        hasAccount: 'Already have an account?',
        loginLink: 'Sign in',
        // Hotel Details
        backToHotels: 'Back to Hotels',
        perNight: '/night',
        aboutHotel: 'About this hotel',
        amenities: 'Amenities',
        bookNow: 'Book Now',
        location: 'Location',
        availability: 'Availability',
        available: 'Available',
        notAvailable: 'Not Available',
        needHelp: 'Need help?',
        contactInfo: 'Contact us for any questions about this hotel',
        contactSupport: 'Contact Support',
        loadingHotel: 'Loading hotel details...',
        hotelNotFound: 'Hotel not found',
        hotelNotFoundText: "The hotel you're looking for could not be found.",
        rating: 'Rating',
        // About Us Page
        aboutUsHero: 'About Us',
        aboutUsSubtitle: 'Discover the story behind Petoria',
        ourStory: 'Our Story',
        ourStoryText: 'Founded with a passion for travel and hospitality, Petoria has been connecting travelers with exceptional accommodations since our inception. We believe that every journey deserves a perfect place to stay, and we\'re committed to making that happen.',
        ourMission: 'Our Mission',
        ourMissionText: 'To provide travelers with seamless access to quality accommodations worldwide, while supporting local hospitality businesses and creating memorable experiences.',
        ourVision: 'Our Vision',
        ourVisionText: 'To become the most trusted platform for hotel bookings, known for our exceptional service, innovative technology, and commitment to sustainable tourism.',
        ourValues: 'Our Values',
        valueQuality: 'Quality',
        valueQualityText: 'We partner only with verified, high-quality hotels to ensure the best experience.',
        valueTrust: 'Trust',
        valueTrustText: 'Transparency and honesty in all our dealings with customers and partners.',
        valueInnovation: 'Innovation',
        valueInnovationText: 'Continuously improving our platform to serve you better.',
        valueSustainability: 'Sustainability',
        valueSustainabilityText: 'Promoting eco-friendly practices in the hospitality industry.',
        meetOurTeam: 'Meet Our Team',
        teamMember1Name: 'John Smith',
        teamMember1Role: 'CEO & Founder',
        teamMember2Name: 'Sarah Johnson',
        teamMember2Role: 'Head of Operations',
        teamMember3Name: 'Michael Chen',
        teamMember3Role: 'Chief Technology Officer',
        teamMember4Name: 'Emily Rodriguez',
        teamMember4Role: 'Customer Experience Lead',
        joinUs: 'Join Us on Our Journey',
        joinUsText: 'Whether you\'re looking for your next getaway or want to partner with us, we\'re here to help.',
        exploreHotels: 'Explore Hotels',
        contactUs: 'Contact Us',
        // User Dropdown Menu
        logout: 'Logout',
        favorites: 'Favorites',
        purchaseHistory: 'Purchase History',
        settings: 'Settings',
        support: 'Support',
        // Settings Page
        settingsTitle: 'Account Settings',
        settingsSubtitle: 'Manage your profile and preferences',
        profileInfo: 'Profile Information',
        updateProfile: 'Update Profile',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        saveChanges: 'Save Changes',
        profileUpdated: 'Profile updated successfully!',
        passwordUpdated: 'Password updated successfully!',
        // Favorites Page
        favoritesTitle: 'My Favorites',
        favoritesSubtitle: 'Hotels you\'ve saved for later',
        noFavorites: 'No favorites yet',
        noFavoritesText: 'Start exploring and save your favorite hotels!',
        removeFromFavorites: 'Remove from favorites',
        // Purchase History Page
        purchaseHistoryTitle: 'Purchase History',
        purchaseHistorySubtitle: 'Your booking history',
        noPurchases: 'No bookings yet',
        noPurchasesText: 'Book your first hotel to see it here!',
        bookingDate: 'Booking Date',
        checkIn: 'Check-in',
        checkOut: 'Check-out',
        totalPrice: 'Total Price',
        status: 'Status',
        confirmed: 'Confirmed',
        pending: 'Pending',
        cancelled: 'Cancelled',
        // Support Page
        supportTitle: 'Customer Support',
        supportSubtitle: 'We\'re here to help',
        contactSupportForm: 'Contact Support',
        yourMessage: 'Your Message',
        subject: 'Subject',
        sendMessage: 'Send Message',
        faqTitle: 'Frequently Asked Questions',
        messageSent: 'Message sent successfully! We\'ll get back to you soon.',
        // Preferences
        preferences: 'Preferences',
        language: 'Language',
        theme: 'Theme',
        currency: 'Currency',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        selectCurrency: 'Select your preferred currency',
        profilePicture: 'Profile Picture',
        uploadPicture: 'Upload Picture',
        removePicture: 'Remove Picture',
        // Navigation
        deals: 'Deals',
        myHotels: 'My Hotels',
        createHotel: 'Create Hotel',
        adminPanel: 'Admin Panel',
        // Common UI
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        search: 'Search',
        viewDetails: 'View Details',
        // Filters & Sorting
        filters: 'Filters',
        sortBy: 'Sort by',
        priceRange: 'Price Range',
        clearFilters: 'Clear Filters',
        applyFilters: 'Apply Filters',
        clearAll: 'Clear All',
        priceRangePerNight: 'Price Range (per night)',
        minRating: 'Minimum Rating',
        searchCountries: 'Search countries...',
        allCountries: 'All Countries',
        searchCities: 'Search cities...',
        allCities: 'All Cities',
        searchAmenities: 'Search amenities...',
        noAmenitiesFound: 'No amenities found',
        selectedCount: '({count} selected)',
        // Hotels Page
        hotelsFound: 'Hotels Found',
        hotelsOnMap: 'Hotels on Map',
        noHotelsFound: 'No hotels found',
        tryAdjustingFilters: 'Try adjusting your filters or search criteria',
        // Deals Page
        lastMinuteDeals: 'Last Minute Deals',
        seasonalDeals: 'Seasonal Deals',
        // Footer
        footerDescription: 'Discover the best hotels and accommodations for your next vacation. Book easily and quickly with Petoria.',
        navigation: 'Navigation',
        supportMenu: 'Support',
        help: 'Help',
        history: 'History',
        contacts: 'Contacts',
        allRightsReserved: 'All rights reserved',
        privacy: 'Privacy',
        terms: 'Terms of Service',
        cookies: 'Cookies',
        // Reviews
        reviews: 'Reviews',
        writeReview: 'Write a Review',
        yourRating: 'Your Rating',
        yourReview: 'Your Review',
        submitReview: 'Submit Review',
        noReviews: 'No reviews yet',
        beFirst: 'Be the first to review this hotel!',
        // My Hotels
        noHotelsYet: 'No hotels yet',
        createFirstHotel: 'Create your first hotel to start accepting reservations.',
        addNewHotel: 'Add New Hotel',
        active: 'Active',
        inactive: 'Inactive',
        manage: 'Manage',
        view: 'View',
        // Purchase History
        myReservations: 'My Reservations',
        reviewHistory: 'Review your past and upcoming reservations',
        noReservationsText: 'You haven\'t made any reservations yet. Browse our hotels!',
        browseHotels: 'Browse Hotels',
        totalAmount: 'Total Amount',
        viewHotel: 'View Hotel',
        cancelReservation: 'Cancel',
        nights: 'nights',
        rooms: 'rooms',
        room: 'room',
        confirmCancelReservation: 'Are you sure you want to cancel this reservation?',
        errorFetchingReservations: 'Error fetching reservations',
        errorCancellingReservation: 'Error cancelling reservation',
        statusConfirmed: 'Confirmed',
        statusPending: 'Pending',
        statusCancelled: 'Cancelled',
        statusCompleted: 'Completed',
        // Create Hotel
        createNewHotel: 'Create New Hotel',
        hotelName: 'Hotel Name',
        description: 'Description',
        city: 'City',
        country: 'Country',
        starRating: 'Star Rating',
        pricePerNight: 'Price Per Night',
        imageUrl: 'Image URL',
        create: 'Create',
        // Deals Page specific
        specialOffers: 'Special Offers',
        discoverDeals: 'Discover incredible promotions and save more',
        discounts: 'Discounts',
        lastMinute: 'Last Minute',
        seasonal: 'Seasonal',
        packages: 'Packages',
        expired: 'Expired',
        // Support Page
        faq1Q: 'How do I make a booking?',
        faq1A: 'Browse our hotels, select your preferred accommodation, choose dates, and click "Book Now". Follow the checkout process to complete your reservation.',
        faq2Q: 'Can I cancel my booking?',
        faq2A: 'Cancellation policies vary by hotel. Check the specific hotel\'s cancellation policy before booking. You can manage your bookings from the Purchase History page.',
        faq3Q: 'How do I change my account settings?',
        faq3A: 'Click on your name in the header, then select "Settings" from the dropdown menu. You can update your profile information and change your password there.',
        faq4Q: 'What payment methods do you accept?',
        faq4A: 'We accept all major credit cards (Visa, MasterCard, American Express) and PayPal for secure online payments.',
        faq5Q: 'How can I contact a hotel directly?',
        faq5A: 'Visit the hotel details page and scroll down to find the contact information section with phone number and email address.',
        email: 'Email',
        phone: 'Phone',
        liveChat: 'Live Chat',
        available24_7: 'Available 24/7',
        // CreateHotel Page
        popularAmenities: 'Popular Amenities',
        customAmenity: 'Custom Amenity',
        addAmenity: 'Add Amenity',
        uploadImages: 'Upload Images',
        mainImage: 'Main Image',
        additionalImages: 'Additional Images',
        uploading: 'Uploading...',
        createHotelButton: 'Create Hotel',
        fillHotelInfo: 'Fill in the hotel information',
        hotelCreatedSuccess: 'Hotel was created successfully!',
        mapLocation: 'Map Location',
        selectLocationDescription: 'Select the exact location of the hotel on the map - the fields for city, country and address will be filled automatically',
        // Admin Dashboard
        superAdminDashboard: 'Super Admin Dashboard',
        manageDashboard: 'Manage users, view statistics, and control admin access',
        loadingDashboard: 'Loading dashboard...',
        totalUsers: 'Total Users',
        admins: 'Admins',
        totalRevenue: 'Total Revenue',
        users: 'Users',
        searchUsers: 'Search users...',
        userDetails: 'User Details',
        removeAdmin: 'Remove Admin',
        promoteToAdmin: 'Promote to Admin',
        totalSpent: 'Total Spent',
        noReservations: 'No reservations yet',
        noHotelsCreated: 'No hotels created',
        noComments: 'No comments yet',
        reservations: 'Reservations',
        comments: 'Comments',
        hotelsCreated: 'Hotels Created',
        onHotel: 'On',
        // ManageHotel Page
        back: 'Back',
        viewPage: 'View Page',
        infoTab: 'Information',
        roomsTab: 'Rooms',
        availabilityTab: 'Availability',
        errorLoadingHotel: 'Error loading hotel',
        errorSaving: 'Error saving',
        savedSuccessfully: 'Saved successfully',
        address: 'Address',
        basePrice: 'Base Price',
        noDescription: 'No description',
        // BookingWidget
        reservation: 'Reservation',
        noRoomsConfigured: 'This hotel has no configured room types yet.',
        pleaseLoginToBook: 'Please log in to make a reservation',
        selectRoomAndDates: 'Please select a room type and dates',
        bookingSuccessful: 'Booking successful! ✓',
        errorLoadingRoomTypes: 'Error loading room types',
        // RoomTypeManager
        roomManagement: 'Room Management',
        initializeAvailability: 'Initialize Availability',
        availabilityInitialized: 'Availability initialized for the next 90 days!',
        errorLoadingRooms: 'Error loading rooms',
        roomName: 'Room Name',
        pricePerNightLabel: 'Price per Night',
        capacityLabel: 'Capacity (guests)',
        totalRoomsLabel: 'Number of Rooms',
        addNewRoomType: 'Add New Room Type',
        editRoom: 'Edit Room',
        fillNameAndPrice: 'Please fill in name and price',
        roomUpdated: 'Room updated successfully!',
        roomAdded: 'Room added successfully!',
        confirmDelete: 'Are you sure you want to delete this room?',
        roomDeleted: 'Room deleted successfully!',

        // BookingWidget Details
        bookNowHeader: 'Book Now',
        roomTypeLabel: 'Room Type',
        guests: 'guests',
        selectDatesLabel: 'Select Dates',

        numberOfRooms: 'Number of Rooms',
        availableRooms: 'Available',
        roomsOfType: 'rooms of this type',
        book: 'Book',
        availableColon: 'Available:',
        checking: 'Checking...',
        originalPrice: 'Original Price',
        youSave: 'You Save',
        total: 'Total',
        booking: 'Booking...',
        bookFor: 'Book for',
        loginToBookWarning: 'You must be logged in to make a reservation',
        // Calendar
        selectCheckInDate: 'Select check-in date',
        weekdaySun: 'Su',
        weekdayMon: 'Mo',
        weekdayTue: 'Tu',
        weekdayWed: 'We',
        weekdayThu: 'Th',
        weekdayFri: 'Fr',
        weekdaySat: 'Sa',
        monthJan: 'January',
        monthFeb: 'February',
        monthMar: 'March',
        monthApr: 'April',
        monthMay: 'May',
        monthJun: 'June',
        monthJul: 'July',
        monthAug: 'August',
        monthSep: 'September',
        monthOct: 'October',
        monthNov: 'November',
        monthDec: 'December',
        legendAvailable: 'Available',
        legendDiscounted: 'Discounted',
        legendSelected: 'Selected',
        legendBlocked: 'Blocked',
        // Deals page - price labels
        perNightSave: 'per night • Save',
        nightsSave: 'nights • Save',
        viewDeal: 'View Deal →',
        // ReviewSection
        averageRating: 'average rating',
        shareYourExperience: 'Share your experience...',
        // Last Minute Deals
        lastRoom: 'Last room!',
        people: 'people',
        checkInColon: 'Check-in:',
        bookNowArrow: 'Book →',
        // CreateHotel - Map & Coordinates
        clickMapToSelect: 'Click on the map to select the hotel location',
        selectLocationOrEnterCoords: 'Select location on map or enter coordinates manually',
        latitude: 'Latitude',
        longitude: 'Longitude',
        loadingAddress: 'Loading address...',
        lat: 'Lat',
        lng: 'Lng',
        addressLabel: 'Address',
        cityLabel: 'City',
        countryLabel: 'Country',
        // CreateHotel - Sections
        basicInformation: 'Basic Information',
        photos: 'Photos',
        roomTypes: 'Room Types',
        // CreateHotel - Form Labels

        descriptionLabel: 'Description',
        locationAddress: 'Location (Address)',
        charactersCount: 'characters',

        star: 'star',
        noCategory: 'No category',
        starsCount: 'stars',
        // CreateHotel - Placeholders
        hotelNamePlaceholder: 'Hotel Paradise',
        cityPlaceholder: 'Sofia',
        countryPlaceholder: 'Bulgaria',
        descriptionPlaceholder: 'Describe the hotel, its features and amenities...',
        addressPlaceholder: '123 Main Street',
        // CreateHotel - Photos
        mainPhoto: 'Main Photo',
        chooseFile: 'Choose File',
        orText: 'or',
        enterURL: 'enter URL',
        additionalPhotos: 'Additional Photos',
        photoURL: 'Photo URL',
        addMorePhoto: '+ Add More Photo',
        // CreateHotel - Amenities
        selectAmenities: 'Select amenities offered by the hotel',
        addCustomAmenity: 'Add your own amenity...',
        addButton: '+ Add',
        selectedAmenities: 'Selected amenities:',
        totalAmenities: 'Total: {count} amenities',
        // CreateHotel - Room Types
        roomTypePlaceholder: 'Room Type 1 (e.g. Single, Double, Suite)',
        roomTypeExample: '(e.g. Single, Double, Suite)',
        roomTypeExample: '(e.g. Single, Double, Suite)',
        addMoreRoomType: '+ Add More Room Type',

        // My Messages Page
        myMessages: 'My Messages',
        myMessagesTitle: 'My Support Messages',
        myMessagesSubtitle: 'History of your questions to hotel administrators',
        noMessagesTitle: 'No messages yet',
        noMessagesText: 'You haven\'t contacted any hotels yet.',
        to: 'To',
        responseReceived: 'Response Received',
        hotelResponse: 'Hotel Response',
        sendAnotherMessage: 'Send Another Message',
        waitingForResponse: 'Waiting for response',
        errorLoadingMessages: 'Error loading messages',

        // Contact Hotel Page
        backToHotel: 'Back to Hotel',
        askQuestion: 'Have a question? Send a message to the hotel administration.',
        messageSentDesc: 'Your message has been sent to the hotel administration. You will be redirected shortly.',
        subjectPlaceholder: 'e.g. Question about parking',
        messagePlaceholder: 'Type your message here...',
        sending: 'Sending...',
        message: 'Message',
        // Admin Support
        supportMessages: 'Support Messages',
        supportMessagesTitle: 'Support Messages',
        noSupportMessages: 'No support messages yet.',
        answered: 'Answered',
        pending: 'Pending',
        yourResponse: 'Your Response',
        writeReplyPlaceholder: 'Write your reply here...',
        sendReply: 'Send Reply',
        errorSendingReply: 'Error sending reply',
        reply: 'Reply',
        superAdmin: 'Petoria Support',
        backToDashboard: 'Back to Dashboard',
    },
    bg: {
        home: 'Начало',
        hotels: 'Хотели',
        destinations: 'Дестинации',
        about: 'За Нас',
        signIn: 'Вход',
        register: 'Регистрация',
        heroTitle: 'Открий Своята',
        heroSubtitle: 'Перфектна Почивка',
        heroText: 'Открийте луксозни хотели и уникални места по света.',
        searchPlaceholder: 'Къде искате да отидете?',
        findPerfectStay: 'Открийте перфектния престой',
        discoverAmazing: 'Открийте невероятни хотели с най-добрите удобства и цени',
        searchBtn: 'Търси',
        popularDestinations: 'Популярни Дестинации',
        destMaldives: 'Малдиви',
        destMaldivesDesc: 'Изживейте върховния лукс в бунгала над водата.',
        destSantorini: 'Санторини, Гърция',
        destSantoriniDesc: 'Спиращи дъха гледки и белосана архитектура.',
        destBali: 'Бали, Индонезия',
        destBaliDesc: 'Тропически рай с богата култура и зашеметяващи плажове.',
        from: 'От',
        night: 'нощувка',
        loginTitle: 'Добре дошли отново',
        loginSubtitle: 'Въведете данните си за достъп',
        emailLabel: 'Имейл Адрес',
        passwordLabel: 'Парола',
        loginBtn: 'Вход',
        noAccount: 'Нямате акаунт?',
        registerLink: 'Регистрирайте се',
        registerTitle: 'Създай Акаунт',
        registerSubtitle: 'Присъединете се към нас за мечтаната ваканция',
        firstNameLabel: 'Име',
        lastNameLabel: 'Фамилия',
        registerBtn: 'Създай Акаунт',
        hasAccount: 'Вече имате акаунт?',
        loginLink: 'Влезте',
        // Hotel Details
        backToHotels: 'Назад към Хотели',
        perNight: '/нощувка',
        aboutHotel: 'За хотела',
        amenities: 'Удобства',
        bookNow: 'Резервирай сега',
        location: 'Локация',
        availability: 'Наличност',
        available: 'Налично',
        notAvailable: 'Не е налично',
        needHelp: 'Нужда от помощ?',
        contactInfo: 'Свържете се с нас за въпроси относно този хотел',
        contactSupport: 'Свържете се с поддръжка',
        loadingHotel: 'Зареждане на детайли за хотела...',
        hotelNotFound: 'Хотелът не е намерен',
        hotelNotFoundText: 'Хотелът, който търсите, не може да бъде намерен.',
        rating: 'Рейтинг',
        // About Us Page
        aboutUsHero: 'За нас',
        aboutUsSubtitle: 'Открийте историята зад Petoria',
        ourStory: 'Нашата история',
        ourStoryText: 'Основани със страст към пътуванията и хотелиерството, Petoria свързва пътуващите с изключителни места за настаняване от самото си създаване. Вярваме, че всяко пътуване заслужава перфектно място за престой и сме ангажирани да направим това възможно.',
        ourMission: 'Нашата мисия',
        ourMissionText: 'Да предоставим на пътуващите безпроблемен достъп до качествени места за настаняване по целия свят, като същевременно подкрепяме местния хотелиерски бизнес и създаваме незабравими преживявания.',
        ourVision: 'Нашата визия',
        ourVisionText: 'Да станем най-доверената платформа за резервации на хотели, позната с изключителното си обслужване, иновативни технологии и ангажираност към устойчив туризъм.',
        ourValues: 'Нашите ценности',
        valueQuality: 'Качество',
        valueQualityText: 'Партнираме само с проверени, висококачествени хотели за най-доброто изживяване.',
        valueTrust: 'Доверие',
        valueTrustText: 'Прозрачност и честност във всичките ни отношения с клиенти и партньори.',
        valueInnovation: 'Иновация',
        valueInnovationText: 'Непрекъснато подобряваме платформата си, за да ви обслужваме по-добре.',
        valueSustainability: 'Устойчивост',
        valueSustainabilityText: 'Промотираме екологични практики в хотелиерската индустрия.',
        meetOurTeam: 'Запознайте се с нашия екип',
        teamMember1Name: 'Иван Петров',
        teamMember1Role: 'Изпълнителен директор и основател',
        teamMember2Name: 'Мария Георгиева',
        teamMember2Role: 'Ръководител операции',
        teamMember3Name: 'Стефан Димитров',
        teamMember3Role: 'Главен технологичен директор',
        teamMember4Name: 'Елена Иванова',
        teamMember4Role: 'Ръководител клиентско обслужване',
        joinUs: 'Присъединете се към нашето пътуване',
        joinUsText: 'Независимо дали търсите следващата си почивка или искате да партнирате с нас, ние сме тук, за да помогнем.',
        exploreHotels: 'Разгледайте хотелите',
        contactUs: 'Свържете се с нас',
        // User Dropdown Menu
        logout: 'Изход',
        favorites: 'Харесани',
        purchaseHistory: 'История на покупки',
        settings: 'Настройки',
        support: 'Съпорт',
        // Settings Page
        settingsTitle: 'Настройки на профила',
        settingsSubtitle: 'Управлявайте профила и предпочитанията си',
        profileInfo: 'Информация за профила',
        updateProfile: 'Актуализирай профила',
        changePassword: 'Смяна на парола',
        currentPassword: 'Текуща парола',
        newPassword: 'Нова парола',
        confirmPassword: 'Потвърди парола',
        saveChanges: 'Запази промените',
        profileUpdated: 'Профилът е актуализиран успешно!',
        passwordUpdated: 'Паролата е променена успешно!',
        // Favorites Page
        favoritesTitle: 'Моите харесани',
        favoritesSubtitle: 'Хотели, които сте запазили за по-късно',
        noFavorites: 'Все още нямате харесани',
        noFavoritesText: 'Започнете да разглеждате и запазете любимите си хотели!',
        removeFromFavorites: 'Премахни от харесани',
        // Purchase History Page
        purchaseHistoryTitle: 'История на покупки',
        purchaseHistorySubtitle: 'Вашата история на резервации',
        noPurchases: 'Все още нямате резервации',
        noPurchasesText: 'Резервирайте вашия първи хотел, за да го видите тук!',
        bookingDate: 'Дата на резервация',
        checkIn: 'Настаняване',
        checkOut: 'Напускане',
        totalPrice: 'Обща цена',
        status: 'Статус',
        confirmed: 'Потвърдена',
        pending: 'В очакване',
        cancelled: 'Отменена',
        // Support Page
        supportTitle: 'Клиентска поддръжка',
        supportSubtitle: 'Ние сме тук, за да помогнем',
        contactSupportForm: 'Свържете се с поддръжката',
        yourMessage: 'Вашето съобщение',
        subject: 'Тема',
        sendMessage: 'Изпрати съобщение',
        faqTitle: 'Често задавани въпроси',
        messageSent: 'Съобщението е изпратено успешно! Ще се свържем с вас скоро.',
        // Preferences
        preferences: 'Предпочитания',
        language: 'Език',
        theme: 'Тема',
        currency: 'Валута',
        darkMode: 'Тъмен режим',
        lightMode: 'Светъл режим',
        selectCurrency: 'Изберете вашата предпочитана валута',
        profilePicture: 'Снимка на профил',
        uploadPicture: 'Качи снимка',
        removePicture: 'Премахни снимка',
        // Navigation
        deals: 'Оферти',
        myHotels: 'Моите хотели',
        createHotel: 'Създай хотел',
        adminPanel: 'Админ панел',
        // Common UI
        loading: 'Зареждане...',
        error: 'Грешка',
        success: 'Успех',
        save: 'Запази',
        cancel: 'Отмени',
        delete: 'Изтрий',
        edit: 'Редактирай',
        search: 'Търси',
        viewDetails: 'Виж детайли',
        // Filters & Sorting
        filters: 'Филтри',
        sortBy: 'Сортирай по',
        priceRange: 'Ценови диапазон',
        clearFilters: 'Изчисти филтрите',
        applyFilters: 'Приложи филтрите',
        clearAll: 'Изчисти всички',
        priceRangePerNight: 'Ценови диапазон (на нощувка)',
        minRating: 'Минимална оценка',
        searchCountries: 'Търсене на държави...',
        allCountries: 'Всички държави',
        searchCities: 'Търсене на градове...',
        allCities: 'Всички градове',
        searchAmenities: 'Търсене на удобства...',
        noAmenitiesFound: 'Няма намерени удобства',
        selectedCount: '({count} избрани)',
        // Hotels Page
        hotelsFound: 'Намерени хотели',
        hotelsOnMap: 'Хотели на картата',
        noHotelsFound: 'Не са намерени хотели',
        tryAdjustingFilters: 'Опитайте да промените филтрите или критериите за търсене',
        // Deals Page
        lastMinuteDeals: 'Оферти в последния момент',
        seasonalDeals: 'Сезонни оферти',
        // Footer
        footerDescription: 'Открийте най-добрите хотели и настанявания за вашата следваща почивка. Резервирайте лесно и бързо с Petoria.',
        navigation: 'Навигация',
        supportMenu: 'Поддръжка',
        help: 'Помощ',
        history: 'История',
        contacts: 'Контакти',
        allRightsReserved: 'Всички права запазени',
        privacy: 'Поверителност',
        terms: 'Условия за ползване',
        cookies: 'Бисквитки',
        // Reviews
        reviews: 'Отзиви',
        writeReview: 'Напиши отзив',
        yourRating: 'Вашата оценка',
        yourReview: 'Вашият отзив',
        submitReview: 'Изпрати отзив',
        noReviews: 'Все още няма отзиви',
        beFirst: 'Бъдете първият, който отзовава за този хотел!',
        // My Hotels
        noHotelsYet: 'Все още нямате хотели',
        createFirstHotel: 'Създайте първия си хотел, за да започнете да приемате резервации.',
        addNewHotel: 'Добави нов хотел',
        active: 'Активен',
        inactive: 'Неактивен',
        manage: 'Управление',
        view: 'Преглед',
        // Purchase History
        myReservations: 'Моите резервации',
        reviewHistory: 'Преглед на вашите минали и предстоящи резервации',
        noReservationsText: 'Все още нямате направени резервации. Разгледайте нашите хотели!',
        browseHotels: 'Разгледай хотели',
        totalAmount: 'Обща сума',
        viewHotel: 'Виж хотел',
        cancelReservation: 'Отмени',
        nights: 'нощувки',
        rooms: 'стаи',
        room: 'стая',
        // Create Hotel
        createNewHotel: 'Създай нов хотел',
        hotelName: 'Име на хотел',
        description: 'Описание',
        city: 'Град',
        country: 'Държава',
        starRating: 'Звездна категория',
        pricePerNight: 'Цена на нощувка',
        imageUrl: 'URL на изображение',
        create: 'Създай',
        // Deals Page specific
        specialOffers: 'Специални Оферти',
        discoverDeals: 'Открийте невероятни промоции и спестете повече',
        discounts: 'Отстъпки',
        lastMinute: 'В последния момент',
        seasonal: 'Сезонни',
        packages: 'Пакети',
        expired: 'Изтекло',
        // Support Page
        faq1Q: 'Как да направя резервация?',
        faq1A: 'Разгледайте нашите хотели, изберете желаното настаняване, изберете дати и кликнете "Резервирай сега". Следвайте процеса на плащане, за да завършите резервацията си.',
        faq2Q: 'Мога ли да откажа резервацията си?',
        faq2A: 'Политиките за анулиране варират според хотела. Проверете конкретната политика за анулиране на хотела преди резервация. Можете да управлявате резервациите си от страницата История на покупки.',
        faq3Q: 'Как да променя настройките на акаунта си?',
        faq3A: 'Кликнете на вашето име в горната част, след това изберете "Настройки" от падащото меню. Можете да актуализирате информацията за профила си и да промените паролата си там.',
        faq4Q: 'Какви методи на плащане приемате?',
        faq4A: 'Приемаме всички основни кредитни карти (Visa, MasterCard, American Express) и PayPal за сигурни онлайн плащания.',
        faq5Q: 'Как мога да се свържа директно с хотел?',
        faq5A: 'Посетете страницата с подробности за хотела и превъртете надолу, за да намерите секцията с контактна информация с телефонен номер и имейл адрес.',
        email: 'Имейл',
        phone: 'Телефон',
        liveChat: 'Чат на живо',
        available24_7: 'Достъпен 24/7',
        // CreateHotel Page
        popularAmenities: 'Популярни удобства',
        customAmenity: 'Персонализирано удобство',
        addAmenity: 'Добави удобство',
        uploadImages: 'Качи изображения',
        mainImage: 'Основно изображение',
        additionalImages: 'Допълнителни изображения',
        uploading: 'Качване...',
        createHotelButton: 'Създай хотел',
        fillHotelInfo: 'Попълнете информацията за новия хотел',
        hotelCreatedSuccess: 'Хотелът беше създаден успешно!',
        mapLocation: 'Местоположение на картата',
        selectLocationDescription: 'Изберете точното местоположение на хотела на картата - полетата за град, държава и адрес ще се попълнят автоматично',
        // Admin Dashboard
        superAdminDashboard: 'Супер Админ Табло',
        manageDashboard: 'Управление на потребители, преглед на статистики и контрол на админ достъп',
        loadingDashboard: 'Зареждане на таблото...',
        totalUsers: 'Всички потребители',
        admins: 'Администратори',
        totalRevenue: 'Общи приходи',
        users: 'Потребители',
        searchUsers: 'Търси потребители...',
        userDetails: 'Детайли за потребител',
        removeAdmin: 'Премахни Админ',
        promoteToAdmin: 'Направи Админ',
        totalSpent: 'Общо похарчено',
        noReservations: 'Все още няма резервации',
        noHotelsCreated: 'Не са създадени хотели',
        noComments: 'Все още няма коментари',
        reservations: 'Резервации',
        comments: 'Коментари',
        hotelsCreated: 'Създадени хотели',
        onHotel: 'За',
        // ManageHotel Page
        back: 'Назад',
        viewPage: 'Преглед на страницата',
        infoTab: 'Информация',
        roomsTab: 'Стаи',
        availabilityTab: 'Наличност',
        errorLoadingHotel: 'Грешка при зареждане на хотела',
        errorSaving: 'Грешка при запазване',
        savedSuccessfully: 'Запазено успешно',
        unavailable: 'Недостъпен',
        address: 'Адрес',
        basePrice: 'Базова цена',
        noDescription: 'Няма описание',
        // BookingWidget
        reservation: 'Резервация',
        noRoomsConfigured: 'Този хотел все още няма конфигурирани типове стаи.',
        pleaseLoginToBook: 'Моля, влезте в акаунта си, за да направите резервация',
        selectRoomAndDates: 'Моля, изберете тип стая и дати',
        bookingSuccessful: 'Резервацията е успешна! ✓',
        errorLoadingRoomTypes: 'Грешка при зареждане на типовете стаи',
        // RoomTypeManager
        roomManagement: 'Управление на стаи',
        initializeAvailability: 'Инициализирай наличност',
        availabilityInitialized: 'Наличността е инициализирана за следващите 90 дни!',
        errorLoadingRooms: 'Грешка при зареждане на стаите',
        roomName: 'Име на стаята',
        pricePerNightLabel: 'Цена на нощувка',
        capacityLabel: 'Капацитет (гости)',
        totalRoomsLabel: 'Брой стаи',
        addNewRoomType: 'Добави нов тип стая',
        editRoom: 'Редактирай стая',
        fillNameAndPrice: 'Моля, попълнете име и цена',
        roomUpdated: 'Стаята е обновена успешно!',
        roomAdded: 'Стаята е добавена успешно!',
        confirmDelete: 'Сигурни ли сте, че искате да изтриете тази стая?',
        roomDeleted: 'Стаята е изтрита успешно!',

        bookNowHeader: 'Резервирай сега',
        roomTypeLabel: 'Тип стая',
        guests: 'гости',
        selectDatesLabel: 'Изберете дати',

        numberOfRooms: 'Брой стаи',
        availableRooms: 'Налични',
        roomsOfType: 'стаи от този тип',
        book: 'Резервирай',
        availableColon: 'Налични:',
        checking: 'Проверка...',
        originalPrice: 'Оригинална цена',
        youSave: 'Спестявате',
        total: 'Общо',
        booking: 'Резервиране...',
        bookFor: 'Резервирай за',
        loginToBookWarning: 'Трябва да влезете в акаунта си, за да направите резервация',
        selectCheckInDate: 'Изберете дата на настаняване',
        weekdaySun: 'Нд',
        weekdayMon: 'Пн',
        weekdayTue: 'Вт',
        weekdayWed: 'Ср',
        weekdayThu: 'Чт',
        weekdayFri: 'Пт',
        weekdaySat: 'Сб',
        monthJan: 'Януари',
        monthFeb: 'Февруари',
        monthMar: 'Март',
        monthApr: 'Април',
        monthMay: 'Май',
        monthJun: 'Юни',
        monthJul: 'Юли',
        monthAug: 'Август',
        monthSep: 'Септември',
        monthOct: 'Октомври',
        monthNov: 'Ноември',
        monthDec: 'Декември',
        legendAvailable: 'Налично',
        legendDiscounted: 'С отстъпка',
        legendSelected: 'Избрано',
        legendBlocked: 'Заето',
        perNightSave: 'на нощувка • Спестете',
        nightsSave: 'нощувки • Спестете',
        viewDeal: 'Виж офертата →',
        averageRating: 'средна оценка',
        shareYourExperience: 'Споделете впечатленията си...',
        lastRoom: 'Последна стая!',
        people: 'души',
        checkInColon: 'Настаняване:',
        bookNowArrow: 'Резервирай →',
        clickMapToSelect: 'Кликнете на картата за избор на местоположението на хотела',
        selectLocationOrEnterCoords: 'Изберете местоположение на картата или въведете координати ръчно',
        latitude: 'Географска ширина (Latitude)',
        longitude: 'Географска дължина (Longitude)',
        loadingAddress: 'Зареждане на адрес...',
        lat: 'Шир',
        lng: 'Дъл',
        addressLabel: 'Адрес',
        cityLabel: 'Град',
        countryLabel: 'Държава',
        basicInformation: 'Основна информация',
        photos: 'Снимки',
        roomTypes: 'Типове стаи',
        descriptionLabel: 'Описание',
        locationAddress: 'Местоположение (Адрес)',
        charactersCount: 'символа',
        star: 'звезда',
        noCategory: 'Без категория',
        starsCount: 'звезди',
        hotelNamePlaceholder: 'Хотел Рай',
        cityPlaceholder: 'София',
        countryPlaceholder: 'България',
        descriptionPlaceholder: 'Опишете хотела, неговите характеристики и удобства...',
        addressPlaceholder: 'ул. Главна 123',
        mainPhoto: 'Основна снимка',
        chooseFile: 'Избери файл',
        orText: 'или',
        enterURL: 'въведи URL',
        additionalPhotos: 'Допълнителни снимки',
        photoURL: 'URL на снимка',
        addMorePhoto: '+ Добави още снимки',
        selectAmenities: 'Изберете удобства, предлагани от хотела',
        addCustomAmenity: 'Добави собствено удобство...',
        addButton: '+ Добави',
        selectedAmenities: 'Избрани удобства:',
        totalAmenities: 'Общо: {count} удобства',
        roomTypePlaceholder: 'Тип стая 1 (напр. Единична, Двойна, Апартамент)',
        roomTypeExample: '(напр. Единична, Двойна, Апартамент)',
        addMoreRoomType: '+ Добави още типове стаи',

        // My Messages Page
        myMessages: 'Моите съобщения',
        myMessagesTitle: 'Моите съобщения',
        myMessagesSubtitle: 'История на вашите въпроси към администраторите на хотели',
        noMessagesTitle: 'Все още няма съобщения',
        noMessagesText: 'Не сте се свързвали с никакви хотели все още.',
        to: 'До',
        responseReceived: 'Получен отговор',
        hotelResponse: 'Отговор от хотел',
        sendAnotherMessage: 'Изпрати друго съобщение',
        waitingForResponse: 'Чака отговор',
        errorLoadingMessages: 'Грешка при зареждане на съобщенията',

        // Contact Hotel Page
        backToHotel: 'Назад към хотела',
        askQuestion: 'Имате въпрос? Изпратете съобщение до администрацията на хотела.',
        messageSentDesc: 'Вашето съобщение беше изпратено до администрацията на хотела. Ще бъдете пренасочени скоро.',
        subjectPlaceholder: 'напр. Въпрос за паркинг',
        messagePlaceholder: 'Напишете вашето съобщение тук...',
        sending: 'Изпращане...',
        message: 'Съобщение',
        lat: 'Lat',
        lng: 'Lng',
        addressLabel: 'Адрес',
        cityLabel: 'Град',
        countryLabel: 'Държава',
        basicInformation: 'Основна информация',
        photos: 'Снимки',
        roomTypes: 'Типове стаи',

        descriptionLabel: 'Описание',
        locationAddress: 'Локация (Адрес)',
        charactersCount: 'символа',

        star: 'звезда',
        noCategory: 'Без категория',
        starsCount: 'звезди',
        hotelNamePlaceholder: 'Hotel Paradise',
        cityPlaceholder: 'София',
        countryPlaceholder: 'България',
        descriptionPlaceholder: 'Опишете хотела, неговите особености и предимства...',
        addressPlaceholder: 'ул. Витоша 123',
        mainPhoto: 'Основна снимка',
        chooseFile: 'Избери файл',
        orText: 'или',
        enterURL: 'въведи URL',
        additionalPhotos: 'Допълнителни снимки',
        photoURL: 'URL на снимка',
        addMorePhoto: '+ Добави още снимка',
        selectAmenities: 'Изберете удобствата, които предлага хотелът',
        addCustomAmenity: 'Добави свое удобство...',
        addButton: '+ Добави',
        selectedAmenities: 'Избрани удобства:',
        totalAmenities: 'Общо: {count} удобства',
        roomTypePlaceholder: 'Тип стая 1 (напр. Единична, Двойна, Апартамент)',
        roomTypeExample: '(напр. Единична, Двойна, Апартамент)',
        addMoreRoomType: '+ Добави още тип стая',
        // Purchase History specific

        confirmCancelReservation: 'Сигурни ли сте, че искате да отмените тази резервация?',
        errorFetchingReservations: 'Грешка при зареждане на резервациите',
        errorCancellingReservation: 'Грешка при отмяна на резервацията',
        statusConfirmed: 'Потвърдена',
        statusPending: 'Изчакваща',
        statusCancelled: 'Отменена',
        statusCompleted: 'Завършена',
        // Admin Support
        supportMessages: 'Съобщения за поддръжка',
        supportMessagesTitle: 'Съобщения за поддръжка',
        noSupportMessages: 'Все още няма съобщения за поддръжка.',
        answered: 'Отговорено',
        pending: 'В очакване',
        yourResponse: 'Вашият отговор',
        writeReplyPlaceholder: 'Напишете отговора си тук...',
        sendReply: 'Изпрати отговор',
        errorSendingReply: 'Грешка при изпращане на отговор',
        reply: 'Отговори',
        superAdmin: 'Petoria Поддръжка',
        backToDashboard: 'Назад към таблото',
    }
};

export const LanguageProvider = ({ children }) => {
    // Initialize language from localStorage or default to 'en'
    const [language, setLanguage] = useState(() => {
        const savedLanguage = localStorage.getItem('language');
        return savedLanguage || 'en';
    });

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage((prev) => {
            const newLang = prev === 'en' ? 'bg' : 'en';
            // Save to localStorage
            localStorage.setItem('language', newLang);
            return newLang;
        });
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
